--- # sample file
- hosts: all
  become: yes
  tasks:
    - name: creating a file
      file:
        path: /home/ansible/saturdayfile
        state: file
    - name: create a directory
      file:
        path: /home/ansible/satdirectory
        state: directory
    - name: copy a file
      copy:
        src: /home/ansible/sundayfile
        dest: /home/ansible


